### ISSUE TITLE
[bug]答题人员积分排行榜最上面的积分详情等无法看全

### ISSUE THREAD

**Issue by iceytea** [zhangxinxu/quiz#22]
链接地址：[https://www.zhangxinxu.com/php/quiz](https://www.zhangxinxu.com/php/quiz)
![image](https://user-images.githubusercontent.com/40764591/56464530-81251b80-641e-11e9-9a0f-188ad4c297f1.png)

**Comment by zhangxinxu** [comment]
感谢反馈
