### ISSUE TITLE
可能有点讨巧吧

### ISSUE THREAD

**Issue by xiejiaxing1994** [zhangxinxu/quiz#70]
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <title>Document</title>
    <style type="text/css">
        
        *{
            margin: 0;
            padding: 0;
        }
        img{
            border:0;
        }
        ol, ul ,li{list-style: none;} 
        .box{
            width: 60%;
            height: : 200px;
            border: 1px solid;
            line-height: 40px;
            margin: 30px auto;
            text-align: center;
            display: flex;
            flex-wrap: nowrap;
            flex-direction: row;
        }
        .wrap{
            width:90%;
            display: flex;
            flex-wrap: wrap;
            flex-direction: row;
            height: 42px;
            overflow: hidden;
        }
        .arrow{
            width: 5%;
            height: 40px;
            border:1px solid red;
            margin: 0 10px;
        }
        .day{
            border: 1px solid blue;
            flex-grow: 1;
        }
    </style>
</head>
<body>
    <div class="box">
        <div class="arrow">&lt;</div>
        <div class="wrap">
            <div class="day">2020年1月-3月</div>
            <div class="day">2020年4月-6月</div>
            <div class="day">2020年度OKR</div>
        </div>
        <div class="arrow">&gt;</div>
    </div>

</body>
</html>`

**Comment by zhangxinxu** [comment]
以评论方式在对应issue下回复哦~
